### ISSUE TITLE
improving the CSV file exporting

### ISSUE THREAD

**Issue by Jeffchiucp** [arrangement-io/arrangethat-io-server#26]
The actual way we want to write out the CSV is very different. But at least there is something in place for now. 

https://github.com/JeffChiu2009/backend-server/blob/aae3cfa91bd933c4dfe7087aab75921180916084/export.py#L10-L11

Here's a screenshot for your reference:

![image](https://user-images.githubusercontent.com/10523517/51629711-24889200-1efd-11e9-847c-9383e7ee0901.png)

**Comment by Jeffchiucp** [comment]
done #29

**Comment by GildedHonour** [comment]
@jeffchiucp Hi. You need help with the "arrangespace-server" repo, right? I can help. Are you interested? Let's discuss.
